In [0]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer


In [0]:
!wget -cq http://www.statmt.org/europarl/v7/fr-en.tgz


In [8]:
!tar -xvzf /content/fr-en.tgz

europarl-v7.fr-en.en
europarl-v7.fr-en.fr


In [0]:
# en_data = pd.read_csv("/content/europarl-v7.it-en.it", delimiter="\n", header=None,error_bad_lines=False)
# en_data.head()

In [9]:
en_data = pd.read_csv("/content/europarl-v7.it-en.en", delimiter="\n", header=None,error_bad_lines=False)
en_data = en_data.rename(columns={0:"sentences"})
en_data["label"] = "en"

en_data.head()

b'Skipping line 6945: expected 1 fields, saw 2\nSkipping line 7277: expected 1 fields, saw 2\nSkipping line 33158: expected 1 fields, saw 2\nSkipping line 38494: expected 1 fields, saw 2\nSkipping line 54570: expected 1 fields, saw 3\nSkipping line 54572: expected 1 fields, saw 2\nSkipping line 87358: expected 1 fields, saw 2\nSkipping line 90384: expected 1 fields, saw 2\nSkipping line 90386: expected 1 fields, saw 2\nSkipping line 105798: expected 1 fields, saw 2\nSkipping line 106458: expected 1 fields, saw 2\nSkipping line 131517: expected 1 fields, saw 2\nSkipping line 131519: expected 1 fields, saw 2\nSkipping line 136696: expected 1 fields, saw 2\nSkipping line 136699: expected 1 fields, saw 2\nSkipping line 139121: expected 1 fields, saw 2\nSkipping line 142552: expected 1 fields, saw 2\nSkipping line 150441: expected 1 fields, saw 2\nSkipping line 158654: expected 1 fields, saw 2\nSkipping line 162394: expected 1 fields, saw 2\nSkipping line 169512: expected 1 fields, saw 2\nS

sentences label
0                          Resumption of the session    en
1  I declare resumed the session of the European ...    en
2  Although, as you will have seen, the dreaded '...    en
3  You have requested a debate on this subject in...    en
4  In the meantime, I should like to observe a mi...    en

In [11]:
fr_data = pd.read_csv("/content/europarl-v7.fr-en.fr", delimiter="\n", header=None,error_bad_lines=False)
fr_data = fr_data.rename(columns={0:"sentences"})
fr_data["label"] = "fr"
fr_data.head()

b'Skipping line 20094: expected 1 fields, saw 2\nSkipping line 27726: expected 1 fields, saw 2\nSkipping line 28814: expected 1 fields, saw 2\nSkipping line 30220: expected 1 fields, saw 2\nSkipping line 30221: expected 1 fields, saw 2\nSkipping line 32604: expected 1 fields, saw 2\nSkipping line 41903: expected 1 fields, saw 2\nSkipping line 53850: expected 1 fields, saw 2\nSkipping line 54949: expected 1 fields, saw 2\nSkipping line 59494: expected 1 fields, saw 4\nSkipping line 59496: expected 1 fields, saw 3\nSkipping line 79555: expected 1 fields, saw 2\nSkipping line 95031: expected 1 fields, saw 2\nSkipping line 95064: expected 1 fields, saw 2\nSkipping line 98382: expected 1 fields, saw 2\nSkipping line 101181: expected 1 fields, saw 2\nSkipping line 114498: expected 1 fields, saw 2\nSkipping line 115143: expected 1 fields, saw 2\nSkipping line 125396: expected 1 fields, saw 8\nSkipping line 128023: expected 1 fields, saw 2\nSkipping line 128626: expected 1 fields, saw 2\nSkipp

sentences label
0                              Reprise de la session    fr
1  Je déclare reprise la session du Parlement eur...    fr
2  Comme vous avez pu le constater, le grand "bog...    fr
3  Vous avez souhaité un débat à ce sujet dans le...    fr
4  En attendant, je souhaiterais, comme un certai...    fr

In [7]:
it_data = pd.read_csv("/content/europarl-v7.it-en.it", delimiter="\n", header=None,error_bad_lines=False)
it_data = it_data.rename(columns={0:"sentences"})
it_data["label"] = "it"
it_data.head()

b'Skipping line 2829: expected 1 fields, saw 2\nSkipping line 6114: expected 1 fields, saw 2\nSkipping line 6943: expected 1 fields, saw 2\nSkipping line 26878: expected 1 fields, saw 2\nSkipping line 28190: expected 1 fields, saw 2\nSkipping line 28191: expected 1 fields, saw 2\nSkipping line 38494: expected 1 fields, saw 2\nSkipping line 41210: expected 1 fields, saw 2\nSkipping line 49400: expected 1 fields, saw 2\nSkipping line 50445: expected 1 fields, saw 2\nSkipping line 54558: expected 1 fields, saw 4\nSkipping line 54560: expected 1 fields, saw 2\nSkipping line 87334: expected 1 fields, saw 2\nSkipping line 90360: expected 1 fields, saw 2\nSkipping line 90362: expected 1 fields, saw 2\nSkipping line 92485: expected 1 fields, saw 2\nSkipping line 92996: expected 1 fields, saw 2\nSkipping line 105766: expected 1 fields, saw 2\nSkipping line 106426: expected 1 fields, saw 2\nSkipping line 116081: expected 1 fields, saw 2\nSkipping line 117318: expected 1 fields, saw 2\nSkipping l

sentences label
0                             Ripresa della sessione    it
1  Dichiaro ripresa la sessione del Parlamento eu...    it
2  Come avrete avuto modo di constatare il grande...    it
3  Avete chiesto che si tenesse una discussione s...    it
4  Nel frattempo è mio desiderio, come del resto ...    it

In [17]:
data = pd.concat([en_data, fr_data, it_data])
data.isnull().sum()
# data


sentences    0
label        0
dtype: int64

In [13]:
data['label'].value_counts()

fr    2003391
it    1878448
en    1859995
Name: label, dtype: int64

sklearn


In [0]:
X = data['sentences']
y = data['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [15]:
count_vect = CountVectorizer()

X_train_counts = count_vect.fit_transform(X_train)
X_train_counts.shape

(3847028, 247013)

In [18]:
tfidf_transformer = TfidfTransformer()

X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape

(3847028, 247013)

In [19]:
# fit our model
from sklearn.svm import LinearSVC
clf = LinearSVC()#c
clf.fit(X_train_tfidf,y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [20]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),
])

# Feed the training data through the pipeline
text_clf.fit(X_train, y_train)  

Pipeline(memory=None,
     steps=[('tfidf', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,...ax_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0))])

In [0]:
# Form a prediction set
predictions = text_clf.predict(X_test)
predictions

In [22]:
# Report the confusion matrix
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[613302    234    366]
 [  1580 659363    360]
 [  1484    197 617920]]


In [23]:
# Print a classification report
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

          en       1.00      1.00      1.00    613902
          fr       1.00      1.00      1.00    661303
          it       1.00      1.00      1.00    619601

   micro avg       1.00      1.00      1.00   1894806
   macro avg       1.00      1.00      1.00   1894806
weighted avg       1.00      1.00      1.00   1894806



In [24]:
# Print the overall accuracy
print(metrics.accuracy_score(y_test,predictions))

0.9977723313099072
